### ISSUE TITLE
WCell.Tools : Terrain extractor - Battlegrounds.xml

### ISSUE THREAD

**Issue by Skizot** [WCell/WCell#1]
Okay, so there is an issue with the terrain extractor (WCell.Tools with the Battleground.xml format).  As there is no log, I can't post-il but I'm maybe gonna make some screenshots later...

**Comment by alexrp** [comment]
Any updates?

**Comment by Skizot** [comment]
Nop.  Still not working for me.

**Comment by alexrp** [comment]
Well, I'm not actually sure what the problem is. Please describe how to reproduce.

**Comment by jaddie** [comment]
The error is caused by the apparently invalid type BattlegroundId in the xml file which is loaded.

**Comment by jaddie** [comment]
Open extractor, try to dump all

**Comment by ghost** [comment]
Open Tools.exe and try terrain export.

**Comment by VillemP** [comment]
Sphex which command are you using.

**Comment by VillemP** [comment]
Fix applied (types from Constants will be mapped separately), however still not sure why Utility doesn't find WCell.Constants assembly in AppDomain.CurrentDomain and map the types along with the rest of the assemblies

**Comment by jaddie** [comment]
Due to being fixed.
-- Closed
