### ISSUE TITLE
UDB-Full-Install.bat should not contain DB information and has wrong paths

### ISSUE THREAD

**Issue by Domiii** [WCell/WCell#11]
1. DB information should be prompted for when executing, else if we change the file, all private information will be commited as well and users won't have to merge changes upon an update
2. Paths need to be changed from:
   %udbdir%SomePath
   to:
   %udbdir%\SomePath

**Comment by jaddie** [comment]
Righto, yeah I'll just get on with the replacement program I've been working on and shove that on, since thats much easier & is dynamic

**Comment by Domiii** [comment]
We could consider writing a simple WCell setup app in C# with a neat little gui, that offers DBC extraction (or DBC path setting), gives an overview over the entire config or at least the important nodes which most certainly have to be modified anyway (eg the DB settings, realmname etc). [GUI should also provide links to the homepage/wiki for help on certain topics]

**Comment by jaddie** [comment]
@ WCell setup app, Yeah I mean im working on making this current DB program fully functional as I said on IRC, but a setup app soounds like a great Idea so after finishing this I'll make another app e.g. WCellSetupManager and then merge this program into that as well and use the mpqtool and extract the dbc and put it in the folder set by the user etc. As usual it will all be on github so people like failers/Tom^ and Mok can chip in and help if they want to contribute etc.

**Comment by jaddie** [comment]
...
