### ISSUE TITLE
List of Issues

### ISSUE THREAD

**Issue by Amonomen** [WCell/WCell#16]
When rotating, casting is interrupted - fixed
Scale issue of npc's and characters, possibly GO's too
Fall dmg
Mana regen - fixed
pvp flag
... more

**Comment by ZaDarkSide** [comment]
Scale issues have nothing to do with WCell, the scales of npcs, gos and characters are stored in DB.

**Comment by pauljenny** [comment]
Perhaps WCell has an incorrect formula for the scale ? Because the scale of the characters isn't stored in DB .

**Comment by ZaDarkSide** [comment]
Table `creature_template` the field is called `scale`.
Table `gameobject_template` the field is called `size`.

**Comment by pauljenny** [comment]
Yes but the users of UDB hasn't got any problems with the scale on Mangos or Trinity ;)

**Comment by ZaDarkSide** [comment]
OK, i will look into this issue, maybe they are read wrong from DB.

**Comment by VillemP** [comment]
on another note, separating these issues into tickets eases tracking our problems

**Comment by Amonomen** [comment]
ZaDarkSide: No actually Wcell uses the property Scalex to determine scale. and its defined in the core as 1
1 is too small and 2 is too large, its an integer as well so no between values.

**Comment by ZaDarkSide** [comment]
So the data is not read from DB at all ? If that is true it must be fixed.

**Comment by ZaDarkSide** [comment]
Ok, asked Domiii about this, tested some random models and the data is read from DB correctly. It is a DB problem not WCell problem. Issue closed.
Please open a separate issue for each problem you have. Don't do LISTS and please give as much detail you can give about the problem.
