### ISSUE TITLE
-- Note :- Don't report issues here anymore Read this issue please ---

### ISSUE THREAD

**Issue by jaddie** [WCell/WCell#17]
Please do not post issues here, they will be closed by me and discarded.
Instead please go to 
http://bugs.wcell.org/
If you need any help please join #wcell on irc.quakenet.org and I will gladly help you if you ask :)

**Comment by darkfr3ak** [comment]
now it worked :)

Thanks for the help.

**Comment by Pepsi1x1** [comment]
great, deleting all comments now
