### ISSUE TITLE
[Bug]UDB_Full_Install.bat

### ISSUE THREAD

**Issue by ramyalexis** [WCell/WCell#2]
UDB_Full_Install.bat has an issue.
We setup this parameter:
set udb-main=UDB_0.12.0_mangos_9582_SD2_1639

but in extract we use this:
7za e -y %udbdir%Full_DB\udb-main.zip -o%udbdir%Full_DB\ but should be
7za e -y %udbdir%Full_DB\%udb-main%.zip -o%udbdir%Full_DB\ or it can't find file...
same with rar
Cheers.

**Comment by ramyalexis** [comment]
Same thing with importing UDB...here it is 
CLS
ECHO.
ECHO.
ECHO [Importing] Started...
ECHO [Importing] UDB database rev 388...
mysql -h %server% --user=%user% --password=%pass% --port=%port% %wdb% < %udbdir%\Full_DB\udb-main.sql
ECHO [Importing] Finished
ECHO.
PAUSE  
GOTO menu

should be %udb-main%

**Comment by jaddie** [comment]
Check my commit rcaa0093
Fixes this issue, thanks for reporting it.

**Comment by ramyalexis** [comment]
yes...seems to be ok now. Thx for quick fix!

**Comment by jaddie** [comment]
np, would have been quicker but only got up 20mins ago :P
