### ISSUE TITLE
Last commit about removing constructor.

### ISSUE THREAD

**Issue by ramyalexis** [WCell/WCell#3]
(00:00:08.0242) [Warn](00:00:08.0242) [Warn] Could not perform FindAll for Account
(00:00:08.0242) [Warn] No default constructor for entity: WCell.AuthServer.Accou
nts.Account
(00:00:08.0242) [Warn](00:00:08.0242) [Warn] Database could not be initialized!
(00:00:08.0242) [Warn] Re-create Database schema? (y/n)
(00:00:08.0242) [Warn] WARNING: This will erase all Accounts!
That's what happend!

**Comment by jaddie** [comment]
Checking this.
