### ISSUE TITLE
[spell] Disengage (ID: 781)

### ISSUE THREAD

**Issue by ghost** [WCell/WCell#36]
Hello,

When I launch Disengage (ID: 781) this message appear : "Spell (781) has not implemented Effect Effect_138. Please report this to the developers"

So i report it !

Bye.

**Comment by Chameleo** [comment]
Wowhead says this effect should be called Jump (2). http://www.wowhead.com/spell=781/disengage
Maybe it can be implemented using knockback packet?

**Comment by jaddie** [comment]
Please report this on the bugtracker at http://bugs.wcell.org/ I have removed the captcha since you were getting issues.

**Comment by Domiii** [comment]
Having logs would be useful
