### ISSUE TITLE
What version of WoW does this run? and Is it still in active development?

### ISSUE THREAD

**Issue by ghost** [WCell/WCell#58]
@Domiii 

I noticed you pushed a change. There is nowhere to post to get information at all on WCell. The forums are dead and ridden with bots and the IRC is all AFK. Hopefully I can get some information since a C# server sounds far superior than a C++ as far as developing standpoints.

**Comment by jaddie** [comment]
Hi Dibes,

Indeed WCell is still alive, it will never die, we just take breaks sometimes although admittedly this one has lasted longer since I've stopped rallying people to get them working on it as I am myself busy, however I am still working on it with Pepsi :)

**Comment by ghost** [comment]
Hey jaddie, do you have a skype? I would love to talk more about this project!

**Comment by jaddie** [comment]
Yeah if you come on IRC I'll pm you it :)
