### ISSUE TITLE
Strange absorb 

### ISSUE THREAD

**Issue by ramyalexis** [WCell/WCell#7]
When i heal myself with priest class for example i see strange absorb in brackets...sometimes it shows "0" sometimes "1"..

**Comment by jaddie** [comment]
It sounds like a borked talent perhaps, try deleting all auras

**Comment by Domiii** [comment]
The problem probably lies with SMSG_ATTACKERSTATEUPDATE, defined in the CombatHandler.
I'll take a look at it soon.

**Comment by vermie** [comment]
3.2 added new field to heal events
http://gist.github.com/434038

**Comment by Domiii** [comment]
Fixed, thanks faramir
